#!/bin/bash -l

#SBATCH -J Deblurring_L0_L2env           # job name
#SBATCH -o job.o%j       # output and error file name (%j expands to jobID)
#SBATCH --nodes=1 
#SBATCH --exclusive
#SBATCH -p main     # queue (partition) -- main, development, etc.

echo $HOSTNAME
pwd


enable_lmod
module load matlab

matlab -nodisplay -nodesktop -batch Main_DeMotionBlurring_Framelet_L0_L2env_SquareLoss